---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canopy-public
  namespace: canopy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/exclude: "true"
  labels:
    app: canopy
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - canopy.eldertree.xyz
    secretName: canopy-cloudflare-origin-tls
  rules:
  - host: canopy.eldertree.xyz
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: canopy-api
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canopy-frontend
            port:
              number: 3000
